### ISSUE TITLE
求联系方式

### ISSUE THREAD

**Issue by ytx0323** [weiaiF/offlineRL-INTERACTION#1]
学长您好，可以留一个邮箱吗？想了解一下您这边自动化所实验室的一些情况。

**Comment by weiaiF** [comment]
你好可以通过这个邮箱联系我



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月08日 19:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [weiaiF/offlineRL-INTERACTION] 求联系方式 (Issue #1) |

学长您好，可以留一个邮箱吗？想了解一下您这边自动化所实验室的一些情况。

**Comment by weiaiF** [comment]
同学你好，可以通过fangxing2022@ia.ac.cn联系我
